modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "tensura_opac"
version = "${version}"
displayName = "TenSura Compat: Open Parties and Claims"
authors = "MinhEragon"
description = '''
Compatibility mod to bridge Tensura:Reincarnated and Open Parties and Claims.
'''
#logoFile = ""

[[dependencies.tensura_opac]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tensura_opac]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tensura_opac]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tensura_opac.mixins.json"
